server:
  port: 8085
  
spring:
  application:
    name: gateway-service
    
    
eureka:
  client:
    service-url:
      defaultZone: http://ec2-13-59-128-22.us-east-2.compute.amazonaws.com:8088/eureka
      
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    
zuul:
  routes:    users:
      path: /users/**
      service-id: user-service
      strip-prefix: false                
  