server:
  port: 1234

spring:  application:    name: school-api
    
  datasource:    driverClassName: org.postgresql.Driver
    initialization-mode: never
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    
  jpa:    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:      ddl-auto: none
    properties:      hibernate: 
        default_schema: ${DB_SCHEMA}
    show-sql: false